language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
  fast_finish: true

sudo: false

cache: vendor

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/sabre-cs-fixer fix . --dry-run --diff

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install
